version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - null
  build:
    commands:
      - echo Building the project...
      - mvn install
  post_build:
    commands:
      - echo Build completed.
artifacts:
  files:
    - target/*.jar
  discard-paths: 'yes'
